FROM quay.io/azavea/franklin:adf474c AS franklin

FROM openjdk:11-jre-slim

RUN \
      addgroup --system franklin \
      && adduser --system --disabled-login --disabled-password \
      --home /var/lib/franklin \
      --shell /sbin/nologin \
      --ingroup franklin \
      -u 1000 \
      franklin

COPY --from=franklin /var/lib/franklin/ /var/lib/franklin/

USER franklin
WORKDIR /var/lib/franklin

ADD ./data-files /var/lib/data-files

ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-jar", "franklin-api-assembly.jar"]