repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: ["--safe"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--strict]
        additional_dependencies: ["pydantic", "types-jsonschema", "types-setuptools", "types-requests"]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
    - id: shellcheck
      args: ["--severity=warning"]