addSbtCoursier
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"                 % "1.3.4")
addSbtPlugin("org.lyranthe.sbt"          % "partial-unification"       % "1.1.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.8")
addSbtPlugin("io.spray"                  % "sbt-revolver"              % "0.9.1")
addSbtPlugin("com.geirsson"              % "sbt-scalafmt"              % "1.5.1")
addSbtPlugin("com.sksamuel.scapegoat"    %% "sbt-scapegoat"            % "1.0.9")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"              % "0.9.8")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"              % "0.14.10")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"               % "0.6.26")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalajs-bundler"       % "0.14.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject"  % "0.6.0")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                  % "2.0.3")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.11")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates"    % "1.2.1")
