// Versions
object Versions {
  val AWSVersion              = "1.11.751"
  val CatsEffectVersion       = "2.1.3"
  val CatsScalacheckVersion   = "0.3.0"
  val CatsVersion             = "2.1.1"
  val CirceFs2Version         = "0.13.0"
  val CirceVersion            = "0.13.0"
  val DeclineVersion          = "1.2.0"
  val DoobieVersion           = "0.9.0"
  val EmojiVersion            = "1.2.1"
  val Flyway                  = "6.4.2"
  val Fs2Version              = "2.4.1"
  val GeoTrellisVersion       = "3.3.0"
  val GeotrellisServerVersion = "4.1.0"
  val GuavaVersion            = "23.0"
  val HikariVersion           = "3.4.5"
  val Http4sVersion           = "0.21.4"
  val JtsVersion              = "1.16.1"
  val Log4CatsVersion         = "1.1.1"
  val MagnoliaVersion         = "0.16.0"
  val MamlVersion             = "0.6.0"
  val Postgis                 = "2.5.0"
  val PureConfig              = "0.12.1"
  val Refined                 = "0.9.14"
  val ScalaLoggingVersion     = "3.9.2"
  val ScalacacheVersion       = "0.28.0"
  val ScalacheckVersion       = "1.14.3"
  val ScapegoatVersion        = "1.3.11"
  val ShapelessVersion        = "2.3.3"
  val Slf4jVersion            = "1.7.30"
  val SourceCodeVersion       = "0.2.1"
  val Specs2Version           = "4.9.4"
  val SpireVersion            = "0.13.0"
  val Stac4SVersion           = "f2ccdf6-SNAPSHOT"
  val SttpModelVersion        = "1.1.3"
  val TapirVersion            = "0.15.3"
}
