#!/bin/bash

set -e

if [[ -n "${FRANKLIN_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

DIR="$(dirname "$0")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build application for staging or a release.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        ./scripts/test

        pushd "${DIR}"

        echo "Building frontend"
        npm install
        npm run build

        echo "Building JAR for API subproject"
        sbt "application/assembly"

        popd

        echo "Building Scala container images"
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            build api
    fi
fi
