#!/bin/bash
set -e

function usage() {
    echo -n \
"Usage: $(basename "$0") SERVICE COMMAND[S]
Use Docker Compose to run a command for a service, or drop into a console.
Example: ./scripts/console
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            bloop console application
            ;;
    esac
fi
