#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Sets up this project for development.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker-compose \
        -f docker-compose.yml \
        run --rm scriptrunner \
        bash -c "pypgstac pgready && python /opt/src/scripts/bin/loadtestdata.py"

fi