#!/bin/bash

set -e

if [[ -n "${FRANKLIN_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0") [flyway command]

Runs app-backend migrations via flywaydb CLI

Available flyway commands are migrate|clean|info|validate|undo|baseline|repair

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[franklin] Running migrations\e[0m"
            ./sbt 'application/run migrate --db-host=localhost'
        docker-compose \
            -f docker-compose.yml \
            run --rm stac \
            bash -c "pypgstac pgready && pypgstac migrate"
            ;;
    esac
fi
