#!/bin/bash

set -e

if [[ -n "${FRANKLIN_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Runs pgstac migrations

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
        docker-compose \
            -f docker-compose.yml \
            run --rm pypgstac \
            bash -c "pypgstac pgready && pypgstac migrate"
            ;;
    esac
fi
