#!/bin/bash

set -e


if [[ -n "${FRANKLIN_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Starts servers using docker-compose.
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[franklin] Starting API service\e[0m"
            docker-compose up
            ;;
    esac
fi
