#!/bin/bash

set -e

if [[ -n "${FRANKLIN_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Attempts to setup the project's development environment.
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then

    case "${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[franklin] Running Setup...\e[0m"
            ./scripts/update
    esac
fi
