#!/bin/bash

set -e


if [[ -n "${FRANKLIN_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Setup external project dependencies.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else

        docker-compose build --pull

        echo "Building Scala assembly JAR"
        docker-compose \
            run --rm --no-deps sbt \
            ";api/assembly"

    fi
fi
