#!/bin/bash

set -e

if [[ -n "${FRANKLIN_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Setup external project dependencies.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    case "${1}" in
    --help)
        usage
        ;;
    *)
        docker-compose up --remove-orphans -d pgstac

        echo -e "\e[32m[franklin] Running migrations...\e[0m"
        ./scripts/migrate

        echo -e "\e[32m[franklin] Loading development data...\e[0m"
        ./scripts/ingest_data
        ;;
    esac
fi
